# Generated by Django 5.2 on 2025-04-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
