# Generated by Django 5.2 on 2025-04-25 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trail',
            name='categ',
            field=models.ManyToManyField(to='trails.category'),
        ),
    ]
