# Generated by Django 5.2 on 2025-10-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='map',
            field=models.TextField(default='', verbose_name='Карта'),
        ),
    ]
