# Generated by Django 5.2 on 2025-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='map',
            field=models.CharField(default='', verbose_name='Карта'),
        ),
    ]
